### ISSUE TITLE
don't use 1.im and 0.im

### ISSUE THREAD

**Issue by stevengj** [bastikr/QuantumOptics.jl#2]
Use `1im` and `0im` or `1.0im` and `0.0im` if you need to enforce a floating-point type (note that e.g. `2.4 + 0im` will already promote to `Complex{Float64}`).  The reason is that the `0.im` syntax may soon be disallowed in Julia 0.6 (JuliaLang/julia#16339).

**Comment by bastikr** [comment]
Thank you for the warning. I changed the code accordingly.
