### ISSUE TITLE
Functions not found

### ISSUE THREAD

**Issue by bradleyashton** [bastikr/QuantumOptics.jl#35]
Hi there, firstly: superb work on this toolbox! 

I am trying to implement some notebooks and find my way around the function structure. A couple of things: 

1. the documentation link from github is (as of today) throwing a 404 error
2. Some of the basic functions don't seem to be available, even though they are part of test scripts that do complete successfully. For example: everything from `nlevel.jl` is absent. For `NLevelBasis`, (called from `test_bases.jl`, apparently successfully?)

If I do

```julia
julia> using QuantumOptics
julia> b=NLevelBasis(3)
ERROR: UndefVarError: NLevelBasis not defined
```

Perhaps I am missing something about the structure of the package, but I can't find out as documentation is not displaying. For example, it would be nice to call `transition` in order to build a particular Hamiltonian... is there another way to do it?

Thanks for any help!

**Comment by david-pl** [comment]
Hey Bradley,
Thanks for the feedback!

1. We're currently building a website and updating the documentation, which required us to move the html files of the documentation. Unfortunately, we forgot to update the links given in the Readme (sorry for that). We will update them shortly, in the meantime you can find the documentation [here](https://bastikr.github.io/QuantumOptics.jl/docs/index.html). Like I said, we are currently updating it, so apologies if some things are not explained in sufficient detail yet.
2. Which version of QuantumOptics are you using? I could reproduce the error by using the latest official release (0.2), i.e. by adding the package with
`julia> Pkg.add("QuantumOptics")`
This version does not contain the `nlevel.jl` module. If you also used the julia package manager to add the package, instead try
`julia> Pkg.clone("https://github.com/bastikr/QuantumOptics.jl.git")`
Note, that it may be necessary to remove the out-of-date package before that with
`julia> Pkg.add("QuantumOptics")`
Alternatively, you can also just use `git` to clone the repository into your Julia path.

I hope this helps. In case it doesn't, please specify which version of QuantumOptics and Julia you are using and which OS you are on, so I can try and reproduce the problem.

**Comment by bastikr** [comment]
Hi!
According to the julia documentation (I didn't test it myself) you can also just do
`julia> Pkg.checkout(pkg)`
to use the master branch.

**Comment by bradleyashton** [comment]
ok, I will stay on master for now, thanks for this
