### ISSUE TITLE
embed

### ISSUE THREAD

**Issue by davidphysdavalos** [bastikr/QuantumOptics.jl#7]
Dear authors of the package, your work is fantasitc. If you have time: I don't understand very well how to use embed() and and BosonicNParticleBasis(), can you give a simple example?. Thanks in advance!

**Comment by bastikr** [comment]
Yeah the documentation for the multi-particle systems is definitively lacking. I hope I come around to improve it in the next few days. The embed function is useful if you have a composite system, e.g. a system consisting of 3 spins. You can define the basis with:

```
b_spin = SpinBasis(1//2)
b = b_spin ⊗ b_spin ⊗ b_spin
```

Assume you want to define an operator in this basis b that only acts onto the second spin. You could do that by doing
```
identityoperator(b_spin) ⊗ sigmap(b_spin) ⊗ identityoperator(b_spin)
```
or equivalently use the embed function
```
embed(b, 2, sigmap(b_spin))
```
Does this make things clear?

**Comment by davidphysdavalos** [comment]
Completely clear now, thank you very much!

**Comment by david-pl** [comment]
Documentation has been updated.
